"""
generate_dashboard.py — Standalone HTML Dashboard
Creates a self-contained HTML file with interactive charts using Plotly.
No Power BI required — open dashboard.html in any browser.

Usage:
    python src/generate_dashboard.py
"""

import pandas as pd
import numpy as np
import json
import os

OUT_PATH = "outputs"
DB_PATH  = "data/ecommerce.db"


def load_outputs():
    """Load all CSV outputs generated by the analytics pipeline."""
    data = {}
    files = {
        "rfm":      "rfm_segments.csv",
        "rfm_sum":  "rfm_segment_summary.csv",
        "clv":      "clv_predictions.csv",
        "churn":    "churn_predictions.csv",
        "forecast": "sales_forecast.csv",
        "products": "product_performance.csv",
    }
    for key, fname in files.items():
        path = os.path.join(OUT_PATH, fname)
        if os.path.exists(path):
            data[key] = pd.read_csv(path)
            print(f"  ✓ {fname}: {len(data[key]):,} rows")
        else:
            print(f"  ✗ Missing: {fname} — run pipeline first")
    return data


def to_js(obj):
    return json.dumps(obj, default=str)


def build_html(data):
    rfm     = data.get("rfm", pd.DataFrame())
    rfm_sum = data.get("rfm_sum", pd.DataFrame())
    clv     = data.get("clv", pd.DataFrame())
    churn   = data.get("churn", pd.DataFrame())
    fc      = data.get("forecast", pd.DataFrame())
    prod    = data.get("products", pd.DataFrame())

    # ── Pre-compute chart data ─────────────────────────────────

    # KPIs
    total_rev    = float(rfm["monetary"].sum()) if not rfm.empty else 0
    total_cust   = int(len(rfm)) if not rfm.empty else 0
    churn_rate   = float(churn["churned"].mean() * 100) if not churn.empty else 0
    avg_clv      = float(clv["clv_12m"].mean()) if not clv.empty else 0
    high_risk    = int((churn["risk_tier"] == "High Risk").sum()) if not churn.empty else 0

    # Segment bar
    if not rfm_sum.empty:
        rfm_sum = rfm_sum.sort_values(by="total_revenue", ascending=False)
    seg_names  = rfm_sum["segment"].tolist()         if not rfm_sum.empty else []
    seg_rev    = rfm_sum["total_revenue"].tolist()   if not rfm_sum.empty else []
    seg_cust   = rfm_sum["customers"].tolist()       if not rfm_sum.empty else []
    seg_colors_map = {
        "Champions":"#2ecc71","Loyal Customers":"#27ae60",
        "Potential Loyalists":"#82e0aa","Promising":"#a9cce3",
        "Need Attention":"#f39c12","About to Sleep":"#f8c471",
        "At Risk":"#e74c3c","Cant Lose Them":"#c0392b",
        "Hibernating":"#aab7b8","Lost":"#717d7e"
    }
    seg_colors = [seg_colors_map.get(s,"#888") for s in seg_names]

    # CLV tier pie
    clv_tiers, clv_counts, clv_revs = [], [], []
    if not clv.empty:
        for tier in ["High Value", "Mid Value", "Low Value"]:
            g = clv[clv["clv_tier"] == tier]
            if not g.empty:
                clv_tiers.append(str(tier))
                clv_counts.append(int(len(g)))
                clv_revs.append(float(g["clv_12m"].sum()))

    # Churn risk donut
    risk_tiers, risk_counts = [], []
    if not churn.empty:
        for tier in ["High Risk", "Medium Risk", "Low Risk"]:
            g = churn[churn["risk_tier"] == tier]
            if not g.empty:
                risk_tiers.append(str(tier))
                risk_counts.append(int(len(g)))
    risk_colors = {"Low Risk":"#2ecc71","Medium Risk":"#f39c12","High Risk":"#e74c3c"}

    # Forecast line
    fc_dates, fc_yhat, fc_lo, fc_hi, fc_actual = [], [], [], [], []
    if not fc.empty:
        fc["ds"] = pd.to_datetime(fc["ds"])
        for _, row in fc.iterrows():
            fc_dates.append(str(row["ds"].date()))
            fc_yhat.append(round(float(row["yhat"]), 2))
            fc_lo.append(round(float(row["yhat_lower"]), 2))
            fc_hi.append(round(float(row["yhat_upper"]), 2))
            fc_actual.append(round(float(row["y"]), 2) if not pd.isna(row.get("y", float("nan"))) else None)

    # Products bar
    prod_cats, prod_rev, prod_abc, prod_review = [], [], [], []
    if not prod.empty:
        top_prod = prod.head(15)
        prod_cats   = top_prod["category"].tolist()
        prod_rev    = top_prod["revenue"].tolist()
        prod_abc    = top_prod["abc_class"].tolist()
        prod_review = top_prod["avg_review"].round(2).tolist()
    abc_color_map = {"A":"#2ecc71","B":"#f39c12","C":"#e74c3c"}
    prod_colors = [abc_color_map.get(c,"#888") for c in prod_abc]

    # Top-10 at-risk customers table
    at_risk_html = ""
    if not churn.empty:
        top_risk = (churn[churn["risk_tier"]=="High Risk"]
                    .nlargest(10,"churn_probability")
                    [["customer_id","churn_probability","total_spend","days_since_last","order_count"]]
                    .round(3))
        rows_html = ""
        for _, r in top_risk.iterrows():
            rows_html += f"""<tr>
              <td>{str(r['customer_id'])[:20]}…</td>
              <td><span class="risk-badge">{r['churn_probability']:.0%}</span></td>
              <td>R$ {r['total_spend']:,.0f}</td>
              <td>{int(r['days_since_last'])} days</td>
              <td>{int(r['order_count'])}</td>
            </tr>"""
        at_risk_html = f"""
        <table class="risk-table">
          <thead><tr>
            <th>Customer ID</th><th>Churn Prob</th>
            <th>Total Spend</th><th>Days Inactive</th><th>Orders</th>
          </tr></thead>
          <tbody>{rows_html}</tbody>
        </table>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>E-Commerce Analytics Platform — Dashboard</title>
<script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>
<style>
  *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
  :root {{
    --bg:      #0f172a;
    --card:    #1e293b;
    --border:  #334155;
    --text:    #e2e8f0;
    --muted:   #94a3b8;
    --green:   #2ecc71;
    --blue:    #3b82f6;
    --red:     #e74c3c;
    --amber:   #f59e0b;
    --purple:  #a855f7;
  }}
  body {{ font-family: 'Segoe UI', system-ui, sans-serif; background: var(--bg); color: var(--text); }}

  /* ── Header ── */
  header {{
    background: linear-gradient(135deg, #1e293b 0%, #0f172a 100%);
    border-bottom: 1px solid var(--border);
    padding: 18px 32px;
    display: flex; align-items: center; gap: 16px;
  }}
  header h1 {{ font-size: 1.3rem; font-weight: 700; color: var(--text); }}
  header .sub {{ font-size: 0.8rem; color: var(--muted); margin-top: 2px; }}
  .badge {{
    background: var(--blue); color: white; font-size: 0.7rem;
    padding: 3px 10px; border-radius: 999px; font-weight: 600;
  }}

  /* ── Nav tabs ── */
  nav {{
    background: var(--card); border-bottom: 1px solid var(--border);
    display: flex; gap: 4px; padding: 0 24px; overflow-x: auto;
  }}
  nav button {{
    background: none; border: none; color: var(--muted); cursor: pointer;
    padding: 14px 20px; font-size: 0.875rem; font-weight: 500;
    border-bottom: 3px solid transparent; white-space: nowrap;
    transition: color .2s, border-color .2s;
  }}
  nav button.active {{ color: var(--blue); border-bottom-color: var(--blue); }}
  nav button:hover:not(.active) {{ color: var(--text); }}

  /* ── Layout ── */
  .page {{ display: none; padding: 24px 28px; }}
  .page.active {{ display: block; }}
  .grid-4 {{ display: grid; grid-template-columns: repeat(4,1fr); gap: 16px; margin-bottom: 20px; }}
  .grid-2 {{ display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 20px; }}
  .grid-3 {{ display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 16px; margin-bottom: 20px; }}
  @media(max-width:900px) {{
    .grid-4, .grid-2, .grid-3 {{ grid-template-columns: 1fr; }}
  }}

  /* ── Cards ── */
  .card {{
    background: var(--card); border: 1px solid var(--border);
    border-radius: 12px; padding: 20px;
  }}
  .card-title {{
    font-size: 0.75rem; font-weight: 600; text-transform: uppercase;
    letter-spacing: 0.05em; color: var(--muted); margin-bottom: 8px;
  }}
  .kpi-value {{ font-size: 2rem; font-weight: 700; line-height: 1.1; }}
  .kpi-sub {{ font-size: 0.8rem; color: var(--muted); margin-top: 4px; }}
  .green {{ color: var(--green); }}
  .red   {{ color: var(--red); }}
  .blue  {{ color: var(--blue); }}
  .amber {{ color: var(--amber); }}

  /* ── Charts ── */
  .chart-wrap {{ min-height: 320px; }}

  /* ── At-risk table ── */
  .risk-table {{ width:100%; border-collapse:collapse; font-size:0.82rem; }}
  .risk-table th {{
    background: #0f172a; color: var(--muted); text-align:left;
    padding: 8px 12px; font-weight:600; border-bottom: 1px solid var(--border);
  }}
  .risk-table td {{ padding: 8px 12px; border-bottom: 1px solid var(--border); }}
  .risk-table tr:hover td {{ background: rgba(255,255,255,0.03); }}
  .risk-badge {{
    background: #7f1d1d; color: #fca5a5; padding: 3px 8px;
    border-radius: 999px; font-weight: 700; font-size: 0.78rem;
  }}

  /* ── Footer ── */
  footer {{
    text-align:center; padding:20px; font-size:0.75rem; color:var(--muted);
    border-top: 1px solid var(--border); margin-top: 8px;
  }}
</style>
</head>
<body>

<header>
  <div>
    <h1>🛒 E-Commerce Customer Analytics Platform</h1>
    <div class="sub">Olist Brazilian E-Commerce · SQL + Python + Power BI</div>
  </div>
  <div style="margin-left:auto; display:flex; gap:8px; align-items:center;">
    <span class="badge">RFM</span>
    <span class="badge" style="background:#7c3aed">CLV</span>
    <span class="badge" style="background:#0891b2">Churn</span>
    <span class="badge" style="background:#065f46">Forecast</span>
  </div>
</header>

<nav>
  <button class="active" onclick="showPage('exec',this)">📊 Executive Summary</button>
  <button onclick="showPage('rfm',this)">👥 Customer Segments</button>
  <button onclick="showPage('clv',this)">💰 Lifetime Value</button>
  <button onclick="showPage('churn',this)">⚠️ Churn Risk</button>
  <button onclick="showPage('forecast',this)">📈 Sales Forecast</button>
  <button onclick="showPage('products',this)">🛍️ Products</button>
</nav>

<!-- ════════════════════════════════════════════ PAGE 1 — EXEC ════ -->
<div class="page active" id="page-exec">
  <div class="grid-4">
    <div class="card">
      <div class="card-title">Total Customers</div>
      <div class="kpi-value blue">{total_cust:,}</div>
      <div class="kpi-sub">Unique buyers analysed</div>
    </div>
    <div class="card">
      <div class="card-title">Total Revenue</div>
      <div class="kpi-value green">R$ {total_rev/1e6:.2f}M</div>
      <div class="kpi-sub">Delivered orders only</div>
    </div>
    <div class="card">
      <div class="card-title">Churn Rate</div>
      <div class="kpi-value red">{churn_rate:.1f}%</div>
      <div class="kpi-sub">180-day inactivity window</div>
    </div>
    <div class="card">
      <div class="card-title">Avg 12M CLV</div>
      <div class="kpi-value amber">R$ {avg_clv:,.0f}</div>
      <div class="kpi-sub">BG/NBD + Gamma-Gamma</div>
    </div>
  </div>

  <div class="grid-2">
    <div class="card">
      <div class="card-title">Revenue by Customer Segment</div>
      <div class="chart-wrap" id="exec-seg-chart"></div>
    </div>
    <div class="card">
      <div class="card-title">Daily Revenue Trend</div>
      <div class="chart-wrap" id="exec-trend-chart"></div>
    </div>
  </div>

  <div class="card" style="padding:20px 24px;">
    <div class="card-title" style="margin-bottom:12px;">★ Key Findings — Resume Impact</div>
    <div style="display:grid; grid-template-columns:repeat(3,1fr); gap:16px; font-size:0.88rem; color:var(--muted);">
      <div>📌 Champions + Loyal Customers = <strong style="color:var(--green)">{rfm_sum[rfm_sum['segment'].isin(['Champions','Loyal Customers'])]['revenue_pct'].sum() if not rfm_sum.empty else 0:.0f}% of revenue</strong></div>
      <div>📌 High-risk churn customers: <strong style="color:var(--red)">{high_risk:,} customers</strong></div>
      <div>📌 Class A products drive <strong style="color:var(--amber)">{prod[prod['abc_class']=='A']['revenue_pct'].sum() if not prod.empty else 0:.0f}% of category revenue</strong></div>
    </div>
  </div>
</div>

<!-- ════════════════════════════════════════════ PAGE 2 — RFM ════ -->
<div class="page" id="page-rfm">
  <div class="grid-2">
    <div class="card">
      <div class="card-title">Customers per Segment</div>
      <div class="chart-wrap" id="rfm-cust-chart"></div>
    </div>
    <div class="card">
      <div class="card-title">Revenue per Segment</div>
      <div class="chart-wrap" id="rfm-rev-chart"></div>
    </div>
  </div>
  <div class="grid-2">
    <div class="card">
      <div class="card-title">Revenue % vs Customer % per Segment</div>
      <div class="chart-wrap" id="rfm-compare-chart"></div>
    </div>
    <div class="card">
      <div class="card-title">RFM Score Distribution (Total Score)</div>
      <div class="chart-wrap" id="rfm-score-chart"></div>
    </div>
  </div>
</div>

<!-- ════════════════════════════════════════════ PAGE 3 — CLV ════ -->
<div class="page" id="page-clv">
  <div class="grid-3">
    <div class="card">
      <div class="card-title">Avg CLV by Tier</div>
      <div class="kpi-value amber">R$ {avg_clv:,.0f}</div>
      <div class="kpi-sub">12-month predicted value</div>
    </div>
    <div class="card">
      <div class="card-title">High-Value Customers</div>
      <div class="kpi-value green">{clv_counts[clv_tiers.index("High Value")] if "High Value" in clv_tiers else 0:,}</div>
      <div class="kpi-sub">Top CLV tier</div>
    </div>
    <div class="card">
      <div class="card-title">Total Projected Revenue</div>
      <div class="kpi-value blue">R$ {clv["clv_12m"].sum()/1e6:.2f}M</div>
      <div class="kpi-sub">All repeat customers · 12 months</div>
    </div>
  </div>
  <div class="grid-2">
    <div class="card">
      <div class="card-title">CLV Tier Distribution</div>
      <div class="chart-wrap" id="clv-pie-chart"></div>
    </div>
    <div class="card">
      <div class="card-title">Projected Revenue by Tier</div>
      <div class="chart-wrap" id="clv-rev-chart"></div>
    </div>
  </div>
  <div class="card">
    <div class="card-title">CLV vs Purchase Frequency (repeat customers)</div>
    <div class="chart-wrap" id="clv-scatter-chart"></div>
  </div>
</div>

<!-- ════════════════════════════════════════════ PAGE 4 — CHURN ════ -->
<div class="page" id="page-churn">
  <div class="grid-3">
    <div class="card">
      <div class="card-title">Overall Churn Rate</div>
      <div class="kpi-value red">{churn_rate:.1f}%</div>
      <div class="kpi-sub">180-day inactivity threshold</div>
    </div>
    <div class="card">
      <div class="card-title">High Risk Customers</div>
      <div class="kpi-value red">{high_risk:,}</div>
      <div class="kpi-sub">Churn probability &gt; 66%</div>
    </div>
    <div class="card">
      <div class="card-title">Low Risk Customers</div>
      <div class="kpi-value green">{int((churn["risk_tier"]=="Low Risk").sum()) if not churn.empty else 0:,}</div>
      <div class="kpi-sub">Churn probability &lt; 33%</div>
    </div>
  </div>
  <div class="grid-2">
    <div class="card">
      <div class="card-title">Churn Risk Tier Breakdown</div>
      <div class="chart-wrap" id="churn-donut-chart"></div>
    </div>
    <div class="card">
      <div class="card-title">Churn Probability Distribution</div>
      <div class="chart-wrap" id="churn-hist-chart"></div>
    </div>
  </div>
  <div class="card">
    <div class="card-title">⚠️ Top 10 High-Risk Customers (Intervention Priority)</div>
    <div style="overflow-x:auto; margin-top:12px;">{at_risk_html}</div>
  </div>
</div>

<!-- ════════════════════════════════════════════ PAGE 5 — FORECAST ════ -->
<div class="page" id="page-forecast">
  <div class="card" style="margin-bottom:20px;">
    <div class="card-title">90-Day Revenue Forecast (Prophet Model)</div>
    <div class="chart-wrap" style="min-height:400px;" id="forecast-chart"></div>
  </div>
  <div class="grid-2">
    <div class="card">
      <div class="card-title">Weekly Revenue Pattern</div>
      <div class="chart-wrap" id="forecast-weekly"></div>
    </div>
    <div class="card">
      <div class="card-title">Monthly Revenue Trend</div>
      <div class="chart-wrap" id="forecast-monthly"></div>
    </div>
  </div>
</div>

<!-- ════════════════════════════════════════════ PAGE 6 — PRODUCTS ════ -->
<div class="page" id="page-products">
  <div class="grid-2">
    <div class="card">
      <div class="card-title">Top 15 Categories by Revenue (ABC Class)</div>
      <div class="chart-wrap" id="prod-rev-chart"></div>
    </div>
    <div class="card">
      <div class="card-title">Review Score vs Revenue</div>
      <div class="chart-wrap" id="prod-scatter-chart"></div>
    </div>
  </div>
  <div class="card">
    <div class="card-title">ABC Classification — Revenue Share</div>
    <div class="chart-wrap" id="prod-abc-chart"></div>
  </div>
</div>

<footer>
  E-Commerce Customer Analytics Platform &nbsp;·&nbsp;
  Built with Python · SQL · Prophet · XGBoost · BG/NBD &nbsp;·&nbsp;
  Dataset: Olist Brazilian E-Commerce
</footer>

<script>
// ─── Data ─────────────────────────────────────────────────────
const SEG_NAMES   = {to_js(seg_names)};
const SEG_REV     = {to_js(seg_rev)};
const SEG_CUST    = {to_js(seg_cust)};
const SEG_COLORS  = {to_js(seg_colors)};
const CLV_TIERS   = {to_js(clv_tiers)};
const CLV_COUNTS  = {to_js(clv_counts)};
const CLV_REVS    = {to_js(clv_revs)};
const RISK_TIERS  = {to_js(risk_tiers)};
const RISK_COUNTS = {to_js(risk_counts)};
const RISK_COLORS = {to_js([risk_colors.get(t,"#888") for t in risk_tiers])};
const FC_DATES    = {to_js(fc_dates)};
const FC_YHAT     = {to_js(fc_yhat)};
const FC_LO       = {to_js(fc_lo)};
const FC_HI       = {to_js(fc_hi)};
const FC_ACTUAL   = {to_js(fc_actual)};
const PROD_CATS   = {to_js(prod_cats)};
const PROD_REV    = {to_js(prod_rev)};
const PROD_COLORS = {to_js(prod_colors)};
const PROD_REVIEW = {to_js(prod_review)};
const PROD_ABC    = {to_js(prod_abc)};

// ─── Theme ────────────────────────────────────────────────────
const THEME = {{
  paper_bgcolor: '#1e293b',
  plot_bgcolor:  '#1e293b',
  font: {{ color: '#e2e8f0', size: 11 }},
  xaxis: {{ gridcolor:'#334155', zerolinecolor:'#334155' }},
  yaxis: {{ gridcolor:'#334155', zerolinecolor:'#334155' }},
  margin: {{ t:30, r:20, b:50, l:80 }},
  showlegend: false
}};
const CFG = {{ responsive:true, displayModeBar:false }};

// ─── Tab navigation ────────────────────────────────────────────
function showPage(id, btn) {{
  document.querySelectorAll('.page').forEach(p => p.classList.remove('active'));
  document.querySelectorAll('nav button').forEach(b => b.classList.remove('active'));
  document.getElementById('page-' + id).classList.add('active');
  btn.classList.add('active');
  renderCharts(id);
}}

// ─── Chart render router ───────────────────────────────────────
const rendered = new Set();
function renderCharts(page) {{
  if (rendered.has(page)) return;
  rendered.add(page);

  if (page === 'exec')     renderExec();
  if (page === 'rfm')      renderRFM();
  if (page === 'clv')      renderCLV();
  if (page === 'churn')    renderChurn();
  if (page === 'forecast') renderForecast();
  if (page === 'products') renderProducts();
}}

// ── Exec ──────────────────────────────────────────────────────
function renderExec() {{
  Plotly.newPlot('exec-seg-chart', [{{
    type:'bar', x: SEG_REV.map(v=>v/1000), y: SEG_NAMES,
    orientation:'h', marker:{{color: SEG_COLORS}},
    hovertemplate: '%{{y}}<br>R$ %{{x:.0f}}K<extra></extra>'
  }}], {{...THEME, xaxis:{{...THEME.xaxis, type:'linear', title:'Revenue (R$ 000s)'}},
    yaxis:{{...THEME.yaxis, type:'category', categoryorder: 'total ascending'}}}}, CFG);

  // Forecast trend
  const actual = FC_DATES.map((d,i) => FC_ACTUAL[i]);
  Plotly.newPlot('exec-trend-chart', [{{
    type:'scatter', mode:'lines', name:'Actual',
    x: FC_DATES, y: actual.map(v => v ? v/1000 : null),
    line:{{color:'#3b82f6',width:2}},
    hovertemplate:'%{{x}}<br>R$ %{{y:.1f}}K<extra></extra>'
  }}, {{
    type:'scatter', mode:'lines', name:'Forecast',
    x: FC_DATES, y: FC_YHAT.map(v=>v/1000),
    line:{{color:'#e74c3c',width:2,dash:'dot'}},
    hovertemplate:'%{{x}}<br>Forecast: R$ %{{y:.1f}}K<extra></extra>'
  }}], {{...THEME, showlegend:true, legend:{{x:0,y:1,bgcolor:'transparent'}},
    xaxis:{{...THEME.xaxis, type:'date'}}, yaxis:{{...THEME.yaxis, type:'linear', title:'Revenue (R$ 000s)'}}}}, CFG);
}}

// ── RFM ──────────────────────────────────────────────────────
function renderRFM() {{
  Plotly.newPlot('rfm-cust-chart', [{{
    type:'bar', y: SEG_CUST, x: SEG_NAMES,
    marker:{{color: SEG_COLORS}},
    hovertemplate: '%{{x}}<br>%{{y}} customers<extra></extra>'
  }}], {{...THEME, xaxis:{{...THEME.xaxis, type:'category', tickangle:-30}},
    yaxis:{{...THEME.yaxis, type:'linear', title:'Customers'}}}}, CFG);

  Plotly.newPlot('rfm-rev-chart', [{{
    type:'bar', y: SEG_REV.map(v=>v/1000), x: SEG_NAMES,
    marker:{{color: SEG_COLORS}},
    hovertemplate:'%{{x}}<br>R$ %{{y:.0f}}K<extra></extra>'
  }}], {{...THEME, xaxis:{{...THEME.xaxis, type:'category', tickangle:-30}},
    yaxis:{{...THEME.yaxis, type:'linear', title:'Revenue (R$ 000s)'}}}}, CFG);

  const total_rev_sum = SEG_REV.reduce((a,b)=>a+b,0);
  const total_cust_sum= SEG_CUST.reduce((a,b)=>a+b,0);
  Plotly.newPlot('rfm-compare-chart', [
    {{type:'bar', name:'Revenue %', x: SEG_NAMES,
      y: SEG_REV.map(v=>+(v/total_rev_sum*100).toFixed(1)),
      marker:{{color:'#3b82f6'}},
      hovertemplate:'Revenue: %{{y}}%<extra></extra>'}},
    {{type:'bar', name:'Customer %', x: SEG_NAMES,
      y: SEG_CUST.map(v=>+(v/total_cust_sum*100).toFixed(1)),
      marker:{{color:'#a855f7'}},
      hovertemplate:'Customers: %{{y}}%<extra></extra>'}}
  ], {{...THEME, showlegend:true, barmode:'group',
    legend:{{x:0,y:1,bgcolor:'transparent'}},
    xaxis:{{...THEME.xaxis, type:'category', tickangle:-30}},
    yaxis:{{...THEME.yaxis, type:'linear', title:'%'}}}}, CFG);

  // Histogram of rfm_total
  const rfmTotals = {to_js(rfm["rfm_total"].tolist()) if not rfm.empty else "[]"};
  Plotly.newPlot('rfm-score-chart', [{{
    type:'histogram', x: rfmTotals, nbinsx:13,
    marker:{{color:'#0891b2'}},
    hovertemplate:'Score %{{x}}<br>%{{y}} customers<extra></extra>'
  }}], {{...THEME, xaxis:{{...THEME.xaxis, type:'linear', title:'RFM Total Score (3–15)'}},
    yaxis:{{...THEME.yaxis, type:'linear', title:'Customers'}}}}, CFG);
}}

// ── CLV ──────────────────────────────────────────────────────
function renderCLV() {{
  const tierColors = {{'Low Value':'#e74c3c','Mid Value':'#f59e0b','High Value':'#2ecc71'}};
  Plotly.newPlot('clv-pie-chart', [{{
    type:'pie', labels: CLV_TIERS, values: CLV_COUNTS,
    marker:{{colors: CLV_TIERS.map(t=>tierColors[t]||'#888')}},
    hole:0.45, textinfo:'label+percent',
    hovertemplate:'%{{label}}<br>%{{value}} customers<extra></extra>'
  }}], {{...THEME, margin:{{t:10,r:10,b:10,l:10}}}}, CFG);

  Plotly.newPlot('clv-rev-chart', [{{
    type:'bar', x: CLV_TIERS, y: CLV_REVS.map(v=>v/1000),
    marker:{{color: CLV_TIERS.map(t=>tierColors[t]||'#888')}},
    hovertemplate:'%{{x}}<br>R$ %{{y:.0f}}K<extra></extra>'
  }}], {{...THEME, xaxis:{{...THEME.xaxis, type:'category'}}, yaxis:{{...THEME.yaxis, type:'linear', title:'Projected CLV (R$ 000s)'}}}}, CFG);

  const clvVals = {to_js(clv["clv_12m"].round(2).tolist()) if not clv.empty else "[]"};
  const freqVals= {to_js(clv["frequency"].tolist()) if not clv.empty else "[]"};
  const tierVals= {to_js(clv["clv_tier"].tolist()) if not clv.empty else "[]"};
  Plotly.newPlot('clv-scatter-chart', [{{
    type:'scatter', mode:'markers',
    x: freqVals, y: clvVals,
    marker:{{ size:5, opacity:0.5,
      color: tierVals.map(t=>tierColors[t]||'#888') }},
    hovertemplate:'Freq: %{{x}}<br>CLV: R$ %{{y:,.0f}}<extra></extra>'
  }}], {{...THEME, xaxis:{{...THEME.xaxis, type:'linear', title:'Purchase Frequency'}},
    yaxis:{{...THEME.yaxis, type:'linear', title:'Predicted 12M CLV (R$)'}}}}, CFG);
}}

// ── Churn ─────────────────────────────────────────────────────
function renderChurn() {{
  Plotly.newPlot('churn-donut-chart', [{{
    type:'pie', labels: RISK_TIERS, values: RISK_COUNTS,
    marker:{{colors: RISK_COLORS}}, hole:0.5,
    textinfo:'label+percent',
    hovertemplate:'%{{label}}<br>%{{value}} customers<extra></extra>'
  }}], {{...THEME, margin:{{t:10,r:10,b:10,l:10}}}}, CFG);

  const probs = {to_js(churn["churn_probability"].round(4).tolist()) if not churn.empty else "[]"};
  Plotly.newPlot('churn-hist-chart', [{{
    type:'histogram', x: probs, nbinsx:40,
    marker:{{color:'#e74c3c',opacity:0.8}},
    hovertemplate:'Prob: %{{x:.2f}}<br>%{{y}} customers<extra></extra>'
  }}], {{...THEME, xaxis:{{...THEME.xaxis, type:'linear', title:'Churn Probability'}},
    yaxis:{{...THEME.yaxis, type:'linear', title:'Customers'}}}}, CFG);
}}

// ── Forecast ──────────────────────────────────────────────────
function renderForecast() {{
  Plotly.newPlot('forecast-chart', [
    {{type:'scatter', mode:'none', name:'Confidence',
      x:[...FC_DATES,...[...FC_DATES].reverse()],
      y:[...FC_HI.map(v=>v/1000),...[...FC_LO].reverse().map(v=>v/1000)],
      fill:'toself', fillcolor:'rgba(59,130,246,0.15)',
      line:{{color:'transparent'}},
      hoverinfo:'skip'}},
    {{type:'scatter', mode:'lines', name:'Actual',
      x: FC_DATES, y: FC_ACTUAL.map(v=>v ? v/1000 : null),
      line:{{color:'#94a3b8',width:1.5}},
      hovertemplate:'%{{x}}<br>Actual: R$ %{{y:.1f}}K<extra></extra>'}},
    {{type:'scatter', mode:'lines', name:'Forecast',
      x: FC_DATES, y: FC_YHAT.map(v=>v/1000),
      line:{{color:'#3b82f6',width:2}},
      hovertemplate:'%{{x}}<br>Forecast: R$ %{{y:.1f}}K<extra></extra>'}}
  ], {{...THEME, showlegend:true, legend:{{x:0,y:1,bgcolor:'transparent'}},
    yaxis:{{...THEME.yaxis, type:'linear', title:'Revenue (R$ 000s)'}},
    xaxis:{{...THEME.xaxis, type:'date'}}}}, CFG);

  // Weekly pattern from actual data
  const weeklyAvg = [0,0,0,0,0,0,0], weeklyN = [0,0,0,0,0,0,0];
  FC_DATES.forEach((d,i) => {{
    if (FC_ACTUAL[i]) {{
      const dow = new Date(d).getDay();
      weeklyAvg[dow] += FC_ACTUAL[i]; weeklyN[dow]++;
    }}
  }});
  const wAvg = weeklyAvg.map((s,i)=>weeklyN[i] ? s/weeklyN[i] : 0);
  Plotly.newPlot('forecast-weekly', [{{
    type:'bar', x:['Sun','Mon','Tue','Wed','Thu','Fri','Sat'],
    y: wAvg.map(v=>v/1000),
    marker:{{color: ['#e74c3c','#3b82f6','#3b82f6','#3b82f6','#3b82f6','#3b82f6','#e74c3c']}},
    hovertemplate:'%{{x}}<br>Avg: R$ %{{y:.1f}}K<extra></extra>'
  }}], {{...THEME, xaxis:{{...THEME.xaxis, type:'category'}}, yaxis:{{...THEME.yaxis, type:'linear', title:'Avg Revenue (R$ 000s)'}}}}, CFG);

  // Monthly
  const monthlyMap = {{}};
  FC_DATES.forEach((d,i) => {{
    if (!FC_ACTUAL[i]) return;
    const m = d.slice(0,7);
    monthlyMap[m] = (monthlyMap[m]||0) + FC_ACTUAL[i];
  }});
  const months = Object.keys(monthlyMap).sort();
  Plotly.newPlot('forecast-monthly', [{{
    type:'scatter', mode:'lines+markers',
    x: months, y: months.map(m=>monthlyMap[m]/1000),
    line:{{color:'#2ecc71',width:2}},
    marker:{{size:6, color:'#2ecc71'}},
    fill:'tozeroy', fillcolor:'rgba(46,204,113,0.1)',
    hovertemplate:'%{{x}}<br>R$ %{{y:.0f}}K<extra></extra>'
  }}], {{...THEME, yaxis:{{...THEME.yaxis, type:'linear', title:'Revenue (R$ 000s)'}},
    xaxis:{{...THEME.xaxis, type:'category', tickangle:-45}}}}, CFG);
}}

// ── Products ──────────────────────────────────────────────────
function renderProducts() {{
  Plotly.newPlot('prod-rev-chart', [{{
    type:'bar', orientation:'h',
    x: [...PROD_REV].reverse().map(v=>v/1000),
    y: [...PROD_CATS].reverse(),
    marker:{{color: [...PROD_COLORS].reverse()}},
    hovertemplate:'%{{y}}<br>R$ %{{x:.0f}}K<extra></extra>'
  }}], {{...THEME, margin:{{...THEME.margin,l:160}},
    xaxis:{{...THEME.xaxis, type:'linear', title:'Revenue (R$ 000s)'}},
    yaxis:{{...THEME.yaxis, type:'category', categoryorder: 'total ascending'}}}}, CFG);

  Plotly.newPlot('prod-scatter-chart', [{{
    type:'scatter', mode:'markers+text',
    x: PROD_REVIEW, y: PROD_REV.map(v=>v/1000),
    text: PROD_CATS.map(c=>c.slice(0,12)),
    textposition:'top center', textfont:{{size:8}},
    marker:{{size:12, color:PROD_COLORS, opacity:0.85,
      line:{{color:'white',width:1}}}},
    hovertemplate:'%{{text}}<br>Review: %{{x}}<br>R$ %{{y:.0f}}K<extra></extra>'
  }}], {{...THEME, xaxis:{{...THEME.xaxis, type:'linear', title:'Avg Review Score (1-5)'}},
    yaxis:{{...THEME.yaxis, type:'linear', title:'Revenue (R$ 000s)'}}}}, CFG);

  const abcMap = {{'A':0,'B':0,'C':0}};
  const abcRevMap = {{'A':0,'B':0,'C':0}};
  PROD_ABC.forEach((c,i)=>{{ abcMap[c]=(abcMap[c]||0)+1; abcRevMap[c]=(abcRevMap[c]||0)+PROD_REV[i]; }});
  Plotly.newPlot('prod-abc-chart', [{{
    type:'pie', labels:['Class A','Class B','Class C'],
    values:[abcRevMap.A/1000, abcRevMap.B/1000, abcRevMap.C/1000],
    marker:{{colors:['#2ecc71','#f59e0b','#e74c3c']}},
    hole:0.4, textinfo:'label+percent+value',
    texttemplate:'%{{label}}<br>%{{percent}}<br>R$ %{{value:.0f}}K',
    hovertemplate:'%{{label}}<br>R$ %{{value:.0f}}K<extra></extra>'
  }}], {{...THEME, margin:{{t:20,r:20,b:20,l:20}}}}, CFG);
}}

// ─── Initial render ───────────────────────────────────────────
renderCharts('exec');
</script>
</body>
</html>"""
    return html


if __name__ == "__main__":
    print("\n" + "="*50)
    print("GENERATING INTERACTIVE DASHBOARD")
    print("="*50 + "\n")

    print("Loading analytics outputs...")
    data = load_outputs()

    print("\nBuilding HTML dashboard...")
    html = build_html(data)

    out_path = f"{OUT_PATH}/dashboard.html"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(html)

    size_kb = os.path.getsize(out_path) / 1024
    print(f"\n✓ Dashboard saved: {out_path} ({size_kb:.0f} KB)")
    print("  Open in any browser — no server needed.")
    print("\n  Pages:")
    print("    📊 Executive Summary")
    print("    👥 Customer Segments (RFM)")
    print("    💰 Customer Lifetime Value")
    print("    ⚠️  Churn Risk")
    print("    📈 Sales Forecast")
    print("    🛍️  Product Performance")
